services:
  es_server:
    image: es_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_TYPE: mariadb
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
    ports:
      - "8080:80"
    env_file: deployment.env
    networks:
      - database
      - internet
    depends_on:
      - es_database
    volumes:
      - type: bind
        source: ${PWD}/../config/config.php
        target: /var/www/config/config.php
        #certbot:
        #image: certbot/certbot:latest
        #volumes:
        #- ./certbot/www/:/var/www/certbot/:rw
        #- ./certbot/conf/:/etc/letsencrypt/:rw
  es_database:
    image: mariadb:10.7
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
volumes:
  db: {}

networks:
  database:
    internal: true
  internet:
